sudo: required
services:
 - docker

before_install:
 - docker build -t gopal07/docker-react -f Dockerfile.dev .

script:
 - docker run gopal07/docker-react -e CI=true npm run test

deploy:
 provider: elasticbeanstalk
 region: "us-east-1"
 app: "Docker-React"
 env: "DockerReact-env "
 bucket_name: "elasticbeanstalk-us-east-1-734171675204"
 bucket_path: "Docker-React"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key:
  secure: "$AWS_SECRET_KEY"
